using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MapFiles
{
    public static List<Map.TileType> DefaultMap = new List<Map.TileType> {
					Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL,
Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL,
Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.SUPERPACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.SUPERPACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL,
Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL,
Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL,
Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL,
Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL,
Map.TileType.TELEPORT, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PACGOMME, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.INVISIBLEWALL, Map.TileType.INVISIBLEWALL, Map.TileType.INVISIBLEWALL, Map.TileType.INVISIBLEWALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PACGOMME, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.TELEPORT,
Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL,
Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.GATE, Map.TileType.GATE, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL,
Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL,
Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL,
Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PATH, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.SUPERPACGOMME, Map.TileType.WALL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.WALL, Map.TileType.SUPERPACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.PACGOMME, Map.TileType.WALL,
Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL, Map.TileType.WALL,
Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL,
Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL,
Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL, Map.TileType.NULL
	};
}
